configmaps:

#  .env file
  - name: authentication
    data: 
      KARTOFFEL_URL: http://kartoffel-master.eastus.cloudapp.azure.com:3001
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      AUTH_CALLBACK_URL: http://localhost:8004/auth/callback
      SESSION_SECRET: very-secret
      SHRAGA_URL: https://shraga-prod.northeurope.cloudapp.azure.com
      SECRET_KEY: supersecret-secret
      TOKEN_KEY: jt-token
      CLIENT_ENDPOINT: http://localhost:80/

# docker-compose.yml file
  - name: api
    data: 
      SERVICES: api
      PORT: "8080"
  - name: user
    data:
      SERVICES: user
  - name: ad
    data:
      AD_SERVICE_DNS: EXAMPLE
      SERVICES: ad
  - name: groupId
    data:
      SERVICES: groupId
  - name: create
    data:
      SERVICES: create
  - name: join
    data:
      SERVICES: join
  - name: owner
    data:
      SERVICES: owner
  - name: mail-builder
    data:
      SERVICES: mail-builder

  - name: mailer-service
    data:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      USE_REDIS: "false"
      USE_AUTH: "false"
      MAIL_HOSTS: "smtp.ethereal.email,smtp.ethereal.email,smtp.ethereal.email,smtp.ethereal.email,smtp.ethereal.email"
      MAIL_USER: selina.mayert92@ethereal.email
      MAIL_PASS: Mdb6ruZm3TPG7Z6Y28
      MAILER_PORT: "25"
      HTTP_SERVER_PORT: "8000"
  
  - name: outgoing-proxy-service
    data:
      MODE: outgoing
      PORT: "8010"
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_CLIENT_ID: aXzoxtIFbLVjebyr0~ppCQFxfsv3ZLNkHBrkyfhz
      SPIKE_CLIENT_SECRET: XUneSMVVJhsGfmVPjjGzZgySdH4hmrNKbXGn5Iupjc68R361v_MuRy_XzBOeCnm3dSNWNU_JBsbWUus7UyVXmvj4cO0GW7am11Ex
      SPIKE_URL: https://ospike.northeurope.cloudapp.azure.com/oauAth2/token
      TOKEN_GRANT_TYPE: client_credentials
      USE_REDIS: 'true'
      OUTGOING_SERVICES: '[{"route":"/kartoffel/*","pathRewrite":{"^/kartoffel":""},"target":"http://kartoffel-master.eastus.cloudapp.azure.com:3001","audience":"kartoffel"}]'

# docker-compose.env 
  - name: moleculer
    data:
      LOGGER: true
      LOGLEVEL: info
      SERVICEDIR: services
      TRANSPORTER: nats://nats:4222
      MONGO_URI: mongodb://mongo/friends-backend
