# Default values for fix-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullSecret:  [ name: friends ]
  ingress:
  enabled: false
    #    annotations:
    #     kubernetes.io/ingress.class: addon-http-application-routing    # delete this inside
    hosts:
      - host: friends.friends.com
        paths: 
        - path: /api
          service: api
          port: "8080"

        - path: /
          service: friends-frontend
          port: "80"

        - path: /auth
          service: authentication-service
          port: "8010"

          
  tls: []
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
